### ISSUE TITLE
Implement job launcher

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi-functional-tests#6]
To run the openqa tests we need a simple job launcher that can do the following in a first version:

1. lookup current integration test images file names and build a map
2. create openqa job taking all or a given set of images into account

**Comment by schaefi** [comment]
There is also the idea floating around to use gitlab CI as launcher since there seems to be some integration with openQA

**Comment by dcermak** [comment]
> There is also the idea floating around to use gitlab CI as launcher since there seems to be some integration with openQA

Turns out I was wrong about the direct integration of gitlab CI with openQA. I have misunderstood how the wicked team uses it and thought that the downstream pipeline would be completely external, but it actually just means that it's a pipeline in an external project on gitlab and not a pipeline on e.g. Jenkins or openQA.

Nevertheless, I think gitlab is still our best bet, mainly given the fact that it supports manually triggered pipelines (i.e. there's a button that you click and then the pipeline is launched). Given that the openQA API replies with the created job ids, we could make the launcher block until all the created jobs finished or failed. That would make this effectively an "external" pipeline.

**Comment by dcermak** [comment]
#2 also includes a launcher and a monitoring script.

**Comment by dcermak** [comment]
Fixed via #10
